name: C++ Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: sudo apt-get install g++

    - name: Build C++ program
      run: g++ main.cpp -o main

    - name: Run the program
      run: ./main