name: C++ Build

on:
  push:
    paths:
      - 'assignments/**'  # Trigger only on changes inside the 'assignments' folder
  pull_request:
    paths:
      - 'assignments/**'  # Trigger only on pull requests with changes in 'assignments' folder

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: assignments  # Check out code into 'assignments' subfolder

    - name: Install build dependencies
      run: sudo apt-get install g++

    - name: Build C++ program in assignments
      working-directory: assignments  # Set working directory to 'assignments'
      run: g++ main.cpp -o main

    - name: Run the program
      working-directory: assignments  # Set working directory to 'assignments'
      run: ./main